name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: Bun version
      run: bun -v
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Node version, npm version
      run: node -v && npm -v
    - name: Bun install
      run: bun install --production
    - name: Bun lint
      run: bun run lint
    - name: Bun build
      run: bun run build
    # - name: Bun start production
    #   run: bun run start
